// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzdittgppnztdpglbfri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6ZGl0dGdwcG56dGRwZ2xiZnJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMjk0NTYsImV4cCI6MjA2NTgwNTQ1Nn0.LbTDTbN51sw2VmWddldVPgm4ZDr8f_lBo0fXDbx3hfo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);